services:
  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user-db-data:/var/lib/postgresql/data
      - ./users/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${USER_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d user_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped
  
  event-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${EVENT_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${EVENT_DB_PASSWORD}
    volumes:
      - event-db-data:/var/lib/postgresql/data
      - ./events/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${EVENT_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d event_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped

  transport-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${TRANSPORT_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${TRANSPORT_DB_PASSWORD}
    volumes:
      - transport-db-data:/var/lib/postgresql/data
      - ./transports/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${TRANSPORT_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d transport_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped

  post-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POST_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POST_DB_PASSWORD}
    volumes:
      - post-db-data:/var/lib/postgresql/data
      - ./posts/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POST_DB_PORT}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d post_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped

volumes:
  user-db-data:
  event-db-data:
  transport-db-data:
  post-db-data:

networks:
  club-manager-network:
    driver: bridge
