services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - club-manager-network
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=8080"
    volumes:
      - ./shared:/shared
    networks:
      - club-manager-network
  
  user-service:
    build:
      context: .
      dockerfile: ./users/src/Dockerfile
    labels:
      - "traefik.enable=false"
    environment:
      DB_URL: "postgres://${DB_USER}:${USER_DB_PASSWORD}@user-db:5432/${USER_DB}?sslmode=disable"
    depends_on:
      user-db:
        condition: service_healthy
    volumes:
      - ./shared:/shared
    networks:
      - club-manager-network
    restart: unless-stopped

  user-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user-db-data:/var/lib/postgresql/data
      - ./users/sql:/docker-entrypoint-initdb.d
    ports:
      - "${USER_DB_PORT}:5432"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d user_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped
  
  event-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${EVENT_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${EVENT_DB_PASSWORD}
    volumes:
      - event-db-data:/var/lib/postgresql/data
      - ./events/sql:/docker-entrypoint-initdb.d
    ports:
      - "${EVENT_DB_PORT}:5432"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d event_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped

  post-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POST_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POST_DB_PASSWORD}
    volumes:
      - post-db-data:/var/lib/postgresql/data
      - ./posts/sql:/docker-entrypoint-initdb.d
    ports:
      - "${POST_DB_PORT}:5432"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d post_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped

  licence-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${LICENCE_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${LICENCE_DB_PASSWORD}
    volumes:
      - licence-db-data:/var/lib/postgresql/data
      - ./licenses/sql:/docker-entrypoint-initdb.d
    ports:
      - "${LICENCE_DB_PORT}:5432"
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U club_manager -d licence_db"]
      interval: 5s 
      timeout: 5s 
      retries: 5 
    networks:
      - club-manager-network
    restart: unless-stopped

volumes:
  user-db-data:
  event-db-data:
  post-db-data:
  licence-db-data:

networks:
  club-manager-network:
    driver: bridge
